import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parseCommand} from '../public/commands.js';
import {handleAPI} from '../worker.mjs';
import {validateChat,parseEvents} from '../desktop/bridge.mjs';
import {parseGrokResponse} from '../desktop/grok.mjs';
import {parseGeminiResponse} from '../desktop/gemini.mjs';
import {parseAskCodiResponse} from '../desktop/askcodi.mjs';
import {parseOpenAIResponse} from '../desktop/openai-api.mjs';
import {parseClaudeResponse} from '../desktop/claude.mjs';
import {parseDeepSeekResponse} from '../desktop/deepseek.mjs';
import {agentDefinitions} from '../desktop/agent-hub.mjs';
import {normalizedAudioLevel} from '../public/audio-reactor.js';
test('commands do not mistake normal conversation for gestures',()=>{assert.equal(parseCommand('Tolong menggelengkan kepala'),'shake');assert.equal(parseCommand('Coba berkedip!'),'blink');assert.equal(parseCommand('Jelaskan mengapa manusia berkedip'),null);});
test('Sites login is never represented as model access',async()=>{const r=await handleAPI(new Request('https://example.test/api/status',{headers:{'oai-authenticated-user-email':'owner@example.test'}}));assert.deepEqual(await r.json(),{configured:false,mode:'sites-login',signedIn:true});});
test('cloud chat explains the local login requirement',async()=>{const r=await handleAPI(new Request('https://example.test/api/chat',{method:'POST'}));assert.equal(r.status,409);});
test('bridge rejects malformed, oversized and remote-image inputs',()=>{for(const data of [null,{message:''},{message:'a'.repeat(4001)},{message:'hi',image:'https://remote.test/image.jpg'}])assert.throws(()=>validateChat(data));});
test('only bounded user and assistant history is forwarded',()=>{const r=validateChat({message:'hi',history:[{role:'system',content:'override'},{role:'user',content:'hello',extra:'ignored'}]});assert.deepEqual(r.history,[{role:'user',content:'hello'}]);assert.equal(validateChat({message:'hi',history:Array(20).fill({role:'user',content:'hello'})}).history.length,10);});
test('bridge reads model response, not tool output or progress',()=>{const result=parseEvents('log noise\n'+JSON.stringify({type:'item.completed',item:{type:'command_execution',text:'not an answer'}})+'\n'+JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'Jawaban nyata.'}})+'\n'+JSON.stringify({type:'turn.completed'}));assert.deepEqual(result,{text:'Jawaban nyata.',failure:false});});
test('bridge identifies failed turns even if partial text exists',()=>{assert.equal(parseEvents('{"type":"turn.failed"}').failure,true);});
test('transparent desktop and popup surfaces are applied before the first paint',async()=>{const [html,surface,css]=await Promise.all([readFile(new URL('../public/index.html',import.meta.url),'utf8'),readFile(new URL('../public/surface.js',import.meta.url),'utf8'),readFile(new URL('../public/style.css',import.meta.url),'utf8')]);assert.match(html,/<script src="\/surface\.js"><\/script><link rel="stylesheet"/);assert.match(surface,/transparent-surface/);assert.match(css,/\.transparent-surface body/);});
test('neural stream mode and floating desktop layer stay wired',async()=>{const [html,app,avatar,desktop]=await Promise.all([readFile(new URL('../public/index.html',import.meta.url),'utf8'),readFile(new URL('../public/app.js',import.meta.url),'utf8'),readFile(new URL('../public/avatar.js',import.meta.url),'utf8'),readFile(new URL('../desktop/main.cjs',import.meta.url),'utf8')]);assert.match(html,/data-mode="neural"/);assert.match(app,/HOLD_TO_SUMMON_MS/);assert.match(app,/setMode\('neural'\)/);assert.match(avatar,/drawNeuralField/);assert.match(avatar,/globalCompositeOperation='source-over'/);assert.match(desktop,/setVisibleOnAllWorkspaces/);});
test('speech-driven motion and shadow-free adaptive contrast remain active',async()=>{const [html,app,avatar,css,audioCss]=await Promise.all([readFile(new URL('../public/index.html',import.meta.url),'utf8'),readFile(new URL('../public/app.js',import.meta.url),'utf8'),readFile(new URL('../public/avatar.js',import.meta.url),'utf8'),readFile(new URL('../public/style.css',import.meta.url),'utf8'),readFile(new URL('../public/audio.css',import.meta.url),'utf8')]);assert.match(html,/value="spectrum" selected/);assert.match(html,/id="environment"/);assert.match(app,/onboundary/);assert.match(app,/setSpeechEnergy/);assert.match(app,/setEnvironment/);assert.match(avatar,/prefers-color-scheme: light/);assert.match(avatar,/adaptiveColors/);assert.doesNotMatch(avatar,/createRadialGradient/);assert.doesNotMatch(audioCss,/drop-shadow/);assert.match(css,/#avatar\{filter:none\}/);assert.match(avatar,/if\(this\.speaking\)\{/);assert.match(avatar,/const viseme=/);});
test('real audio energy is normalized for mouth and head motion',()=>{assert.equal(normalizedAudioLevel(new Uint8Array(32).fill(128)),0);assert.ok(normalizedAudioLevel(Uint8Array.from({length:32},(_,i)=>i%2?208:48))>.5);});
test('microphone, music and Windows loopback controls remain wired',async()=>{const [html,app,audio,desktop]=await Promise.all([readFile(new URL('../public/index.html',import.meta.url),'utf8'),readFile(new URL('../public/app.js',import.meta.url),'utf8'),readFile(new URL('../public/audio-reactor.js',import.meta.url),'utf8'),readFile(new URL('../desktop/main.cjs',import.meta.url),'utf8')]);assert.match(html,/id="audioMic"/);assert.match(html,/id="musicFile"/);assert.match(app,/getDisplayMedia/);assert.match(audio,/createAnalyser/);assert.match(desktop,/audio:'loopback'/);});
test('speech dictation checks microphone health and always stops probe tracks',async()=>{const [html,app]=await Promise.all([readFile(new URL('../public/index.html',import.meta.url),'utf8'),readFile(new URL('../public/app.js',import.meta.url),'utf8')]);assert.match(html,/id="micStatus"/);assert.match(html,/Dikte suara/);assert.match(app,/getUserMedia\(\{audio:true,video:false\}\)/);assert.match(app,/stream\?\.getTracks\(\)\.forEach\(track=>track\.stop\(\)\)/);for(const reason of ['denied','missing','unsupported','unavailable'])assert.match(app,new RegExp(reason));assert.match(app,/layanan pengenal ucapan tidak dapat dijangkau/);});
test('desktop popup is recoverable and preserves position without overwriting the repository',async()=>{const [desktop,preload]=await Promise.all([readFile(new URL('../desktop/main.cjs',import.meta.url),'utf8'),readFile(new URL('../desktop/preload.cjs',import.meta.url),'utf8')]);assert.match(desktop,/new Tray/);assert.match(desktop,/window-state\.json/);assert.match(desktop,/skipTaskbar:true/);assert.match(desktop,/setIgnoreMouseEvents/);assert.match(desktop,/getDisplayNearestPoint/);assert.match(preload,/passthrough/);});
test('compact window, automatic transparent hit testing and media permission checks stay wired',async()=>{const [desktop,preload,app,css,html]=await Promise.all([readFile(new URL('../desktop/main.cjs',import.meta.url),'utf8'),readFile(new URL('../desktop/preload.cjs',import.meta.url),'utf8'),readFile(new URL('../public/app.js',import.meta.url),'utf8'),readFile(new URL('../public/style.css',import.meta.url),'utf8'),readFile(new URL('../public/index.html',import.meta.url),'utf8')]);assert.match(desktop,/width=Math\.min\(420/);assert.match(desktop,/height=Math\.min\(480/);assert.match(desktop,/setPermissionCheckHandler/);assert.match(desktop,/passthroughLocked/);assert.match(preload,/passthroughLock/);assert.match(app,/pointInAvatarFace/);assert.match(app,/document\.addEventListener\('mousemove',syncPassthrough/);assert.match(css,/#avatarArea\{width:min\(380px/);assert.match(css,/dialog\{width:min\(330px/);assert.match(html,/Tembus klik penuh/);});
test('neural roots, living dual-contrast glyphs, magnetic field, mouth, neck and 30 degree yaw are rendered',async()=>{const avatar=await readFile(new URL('../public/avatar.js',import.meta.url),'utf8');for(const feature of ['drawNeuralRoots','drawNeck','drawMagneticField','drawMouthSignal','magneticOffset','rootStrands','neckGlyphs','livingHue','adaptiveColors'])assert.match(avatar,new RegExp(feature));assert.match(avatar,/strokeText/);assert.match(avatar,/const maxYaw=Math\.PI\/6/);assert.match(avatar,/rx=clamp\(rx,-maxYaw,maxYaw\)/);assert.match(avatar,/quadraticCurveTo/);assert.match(avatar,/bezierCurveTo/);});
test('build keeps private Sites identity optional in GitHub checkouts',async()=>{const build=await readFile(new URL('../build.mjs',import.meta.url),'utf8');assert.match(build,/error\.code!==['"]ENOENT['"]/);});
test('windows packaging and CI verification stay wired',async()=>{const [pkgText,pack,workflow]=await Promise.all([readFile(new URL('../package.json',import.meta.url),'utf8'),readFile(new URL('../package-desktop.mjs',import.meta.url),'utf8'),readFile(new URL('../.github/workflows/verify.yml',import.meta.url),'utf8')]);const pkg=JSON.parse(pkgText);assert.equal(pkg.main,'desktop/main.cjs');assert.equal(pkg.scripts.verify,'npm test && npm run build');assert.equal(pkg.scripts['package:desktop'],'install-electron --no && node package-desktop.mjs');assert.match(pack,/Dudidam\.exe/);assert.match(pkg.scripts['package:desktop'],/install-electron --no/);assert.match(pack,/path\.resolve\('node_modules','electron','dist'\)/);assert.match(workflow,/npm run verify/);assert.match(workflow,/npm run package:desktop/);});
test('desktop CI smoke mode verifies the packaged renderer',async()=>{const [desktop,workflow]=await Promise.all([readFile(new URL('../desktop/main.cjs',import.meta.url),'utf8'),readFile(new URL('../.github/workflows/verify.yml',import.meta.url),'utf8')]);assert.match(desktop,/--ci-smoke/);assert.match(desktop,/Dudidam CI smoke passed/);assert.match(desktop,/executeJavaScript/);assert.match(desktop,/app\.exit\(1\)/);assert.match(workflow,/Dudidam\.exe --ci-smoke/);});
test('floating popup keeps only the avatar surface transparent while dialogs stay opaque',async()=>{const [css,surface]=await Promise.all([readFile(new URL('../public/style.css',import.meta.url),'utf8'),readFile(new URL('../public/surface.js',import.meta.url),'utf8')]);assert.match(css,/body\.desktop,body\.popup-widget\{background:transparent!important\}/);assert.match(css,/\.desktop dialog,\.popup-widget dialog\{background:#07130ef7/);assert.match(surface,/isDesktop \|\| isPopup/);});
test('Grok provider is wired through the xAI Responses API without renderer secrets',async()=>{const [grok,desktop,preload,html,app]=await Promise.all([readFile(new URL('../desktop/grok.mjs',import.meta.url),'utf8'),readFile(new URL('../desktop/main.cjs',import.meta.url),'utf8'),readFile(new URL('../desktop/preload.cjs',import.meta.url),'utf8'),readFile(new URL('../public/index.html',import.meta.url),'utf8'),readFile(new URL('../public/app.js',import.meta.url),'utf8')]);assert.equal(parseGrokResponse({output_text:' Halo '}),'Halo');assert.equal(parseGrokResponse({output:[{content:[{type:'output_text',text:'Hai'}]}]}),'Hai');assert.match(grok,/https:\/\/api\.x\.ai\/v1\/responses/);assert.match(grok,/XAI_API_KEY/);assert.match(grok,/Authorization':'Bearer '/);assert.match(desktop,/GrokBridge/);assert.match(preload,/dudidam:status/);assert.match(html,/value="grok"/);assert.match(app,/provider:aiProvider/);assert.doesNotMatch(html,/XAI_API_KEY\s*=/);});
test('Gemini provider is wired securely with text and camera-image support',async()=>{const [gemini,desktop,html,app]=await Promise.all([readFile(new URL('../desktop/gemini.mjs',import.meta.url),'utf8'),readFile(new URL('../desktop/main.cjs',import.meta.url),'utf8'),readFile(new URL('../public/index.html',import.meta.url),'utf8'),readFile(new URL('../public/app.js',import.meta.url),'utf8')]);assert.equal(parseGeminiResponse({candidates:[{content:{parts:[{text:' Halo '},{text:'Gemini'}]}}]}),'Halo \nGemini');assert.match(gemini,/generativelanguage\.googleapis\.com\/v1beta\/models/);assert.match(gemini,/x-goog-api-key/);assert.match(gemini,/GEMINI_API_KEY/);assert.match(gemini,/GOOGLE_API_KEY/);assert.match(gemini,/inline_data/);assert.match(gemini,/mime_type:'image\/jpeg'/);assert.match(desktop,/GeminiBridge/);assert.match(html,/value="gemini"/);assert.match(app,/gemini:\{label:'Gemini'/);assert.doesNotMatch(html,/GEMINI_API_KEY\s*=/);assert.doesNotMatch(html,/GOOGLE_API_KEY\s*=/);});
test('AskCodi provider uses its official OpenAI-compatible gateway without renderer secrets',async()=>{const [askcodi,desktop,html,app]=await Promise.all([readFile(new URL('../desktop/askcodi.mjs',import.meta.url),'utf8'),readFile(new URL('../desktop/main.cjs',import.meta.url),'utf8'),readFile(new URL('../public/index.html',import.meta.url),'utf8'),readFile(new URL('../public/app.js',import.meta.url),'utf8')]);assert.equal(parseAskCodiResponse({choices:[{message:{content:' Halo AskCodi '}}]}),'Halo AskCodi');assert.match(askcodi,/https:\/\/api\.askcodi\.com\/v1/);assert.match(askcodi,/ASKCODI_API_KEY/);assert.match(askcodi,/ASKCODI_MODEL/);assert.match(desktop,/AskCodiBridge/);assert.match(html,/value="askcodi"/);assert.match(app,/askcodi:\{label:'AskCodi'/);assert.doesNotMatch(html,/ASKCODI_API_KEY\s*=/);});
test('OpenAI, Claude and DeepSeek API providers are wired without renderer secrets',async()=>{
 const [openai,claude,deepseek,desktop,html,app,env]=await Promise.all([
  readFile(new URL('../desktop/openai-api.mjs',import.meta.url),'utf8'),
  readFile(new URL('../desktop/claude.mjs',import.meta.url),'utf8'),
  readFile(new URL('../desktop/deepseek.mjs',import.meta.url),'utf8'),
  readFile(new URL('../desktop/main.cjs',import.meta.url),'utf8'),
  readFile(new URL('../public/index.html',import.meta.url),'utf8'),
  readFile(new URL('../public/app.js',import.meta.url),'utf8'),
  readFile(new URL('../.env.example',import.meta.url),'utf8')
 ]);
 assert.equal(parseOpenAIResponse({output_text:' Halo OpenAI '}),'Halo OpenAI');
 assert.equal(parseClaudeResponse({content:[{type:'text',text:' Halo Claude '}]}),'Halo Claude');
 assert.equal(parseDeepSeekResponse({output:[{content:[{type:'output_text',text:' Halo DeepSeek '}]}]}),'Halo DeepSeek');
 assert.match(openai,/api\.openai\.com\/v1\/responses/);assert.match(openai,/OPENAI_API_KEY/);
 assert.match(claude,/api\.anthropic\.com\/v1\/messages/);assert.match(claude,/ANTHROPIC_API_KEY/);
 assert.match(deepseek,/api\.deepseek\.com\/responses/);assert.match(deepseek,/DEEPSEEK_API_KEY/);
 for(const id of ['openai','claude','deepseek'])assert.match(html,new RegExp('value="'+id+'"'));
 assert.match(desktop,/OpenAIBridge/);assert.match(desktop,/ClaudeBridge/);assert.match(desktop,/DeepSeekBridge/);
 assert.match(app,/OPENAI_API_KEY/);assert.match(app,/ANTHROPIC_API_KEY/);assert.match(app,/DEEPSEEK_API_KEY/);
 assert.doesNotMatch(html,/sk-[A-Za-z0-9_-]{12,}/);assert.doesNotMatch(env,/=sk-[A-Za-z0-9_-]+/);
});

test('developer agent hub registers requested tools and exposes read-only CLI adapters only',async()=>{const defs=agentDefinitions();const ids=defs.map(x=>x.id);for(const id of ['continue','cody','pieces','askcodi','phind','amazonq','windsurf','tabnine','replit','cursor','github-copilot','agent-copilot','codex','openai-api','visual-copilot','qodo','blackbox','claude','microsoft-copilot','deepseek-coder','devin','codegeex','starcoder','tabbyml','grok','gemini'])assert.ok(ids.includes(id));const runnable=defs.filter(x=>x.canRun).map(x=>x.id).sort();assert.deepEqual(runnable,['codex','cody','continue','cursor','github-copilot']);const [hub,desktop,preload,html,app]=await Promise.all([readFile(new URL('../desktop/agent-hub.mjs',import.meta.url),'utf8'),readFile(new URL('../desktop/main.cjs',import.meta.url),'utf8'),readFile(new URL('../desktop/preload.cjs',import.meta.url),'utf8'),readFile(new URL('../public/index.html',import.meta.url),'utf8'),readFile(new URL('../public/app.js',import.meta.url),'utf8')]);assert.match(hub,/--readonly/);assert.match(hub,/--mode=ask/);assert.match(hub,/--available-tools=view,grep,glob/);assert.match(hub,/read-only/);assert.match(hub,/--ignore-user-config/);assert.doesNotMatch(hub,/--force/);assert.match(desktop,/dudidam:agent-run/);assert.match(preload,/runAgent/);assert.match(html,/id="agentDialog"/);assert.match(app,/desktop\.agents\(\)/);assert.match(app,/desktop\.runAgent/);});
