import test from 'node:test';
import assert from 'node:assert/strict';
import {parseCommand} from '../public/commands.js';
import {handleAPI} from '../worker.mjs';
import {validateChat,parseEvents} from '../desktop/bridge.mjs';
import {prepareSpeechText} from '../desktop/speech.mjs';
test('commands do not mistake normal conversation for gestures',()=>{assert.equal(parseCommand('Tolong menggelengkan kepala'),'shake');assert.equal(parseCommand('Coba berkedip!'),'blink');assert.equal(parseCommand('Jelaskan mengapa manusia berkedip'),null);});
test('Sites login is never represented as model access',async()=>{const r=await handleAPI(new Request('https://example.test/api/status',{headers:{'oai-authenticated-user-email':'owner@example.test'}}));assert.deepEqual(await r.json(),{configured:false,mode:'sites-login',signedIn:true});});
test('cloud chat explains the local login requirement',async()=>{const r=await handleAPI(new Request('https://example.test/api/chat',{method:'POST'}));assert.equal(r.status,409);});
test('bridge rejects malformed, oversized and remote-image inputs',()=>{for(const data of [null,{message:''},{message:'a'.repeat(4001)},{message:'hi',image:'https://remote.test/image.jpg'}])assert.throws(()=>validateChat(data));});
test('only bounded user and assistant history is forwarded',()=>{const r=validateChat({message:'hi',history:[{role:'system',content:'override'},{role:'user',content:'hello',extra:'ignored'}]});assert.deepEqual(r.history,[{role:'user',content:'hello'}]);assert.equal(validateChat({message:'hi',history:Array(20).fill({role:'user',content:'hello'})}).history.length,10);});
test('bridge reads model response, not tool output or progress',()=>{const result=parseEvents('log noise\n'+JSON.stringify({type:'item.completed',item:{type:'command_execution',text:'not an answer'}})+'\n'+JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'Jawaban nyata.'}})+'\n'+JSON.stringify({type:'turn.completed'}));assert.deepEqual(result,{text:'Jawaban nyata.',failure:false});});
test('bridge identifies failed turns even if partial text exists',()=>{assert.equal(parseEvents('{"type":"turn.failed"}').failure,true);});
test('spoken replies are cleaned for natural Windows speech',()=>{assert.equal(prepareSpeechText('## Jawaban\n- Buka [panduan](https://example.test).\n- Kunjungi https://example.test/help'), 'Jawaban Buka panduan. Kunjungi tautan');assert.throws(()=>prepareSpeechText(''));assert.throws(()=>prepareSpeechText('a'.repeat(12001)));});
