const {contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('dudidamDesktop',Object.freeze({
 status:provider=>ipcRenderer.invoke('dudidam:status',provider),
 ask:payload=>ipcRenderer.invoke('dudidam:ask',payload),
 login:()=>ipcRenderer.invoke('dudidam:login'),
 loginCopilot:()=>ipcRenderer.invoke('dudidam:login-copilot'),
 sttStatus:()=>ipcRenderer.invoke('dudidam:stt-status'),
 transcribe:payload=>ipcRenderer.invoke('dudidam:transcribe',payload),
 ttsStatus:()=>ipcRenderer.invoke('dudidam:tts-status'),
 synthesize:payload=>ipcRenderer.invoke('dudidam:synthesize',payload),
 openPanel:view=>ipcRenderer.send('dudidam:panel-open',view),
 closePanel:()=>ipcRenderer.send('dudidam:panel-close'),
 onPanelView:callback=>{if(typeof callback!=='function')return()=>{};const handler=(_event,view)=>callback(view);ipcRenderer.on('dudidam:panel-view',handler);return()=>ipcRenderer.removeListener('dudidam:panel-view',handler);},
 agents:()=>ipcRenderer.invoke('dudidam:agents'),
 chooseProjectRoot:()=>ipcRenderer.invoke('dudidam:project-root-choose'),
 runAgent:payload=>ipcRenderer.invoke('dudidam:agent-run',payload),
 openAgent:id=>ipcRenderer.invoke('dudidam:agent-open',id),
 center:()=>ipcRenderer.send('dudidam:center'),
 move:delta=>ipcRenderer.send('dudidam:move',delta),
 passthrough:value=>ipcRenderer.send('dudidam:passthrough',value),
 passthroughLock:value=>ipcRenderer.send('dudidam:passthrough-lock',value),
 avatarViewport:value=>ipcRenderer.send('dudidam:avatar-viewport',value),
 panelViewport:value=>ipcRenderer.send('dudidam:panel-viewport',value),
 minimize:()=>ipcRenderer.send('dudidam:minimize'),
 close:()=>ipcRenderer.send('dudidam:close'),
 finishDismiss:reason=>ipcRenderer.send('dudidam:dismiss-complete',reason),
 onShow:callback=>{if(typeof callback!=='function')return()=>{};const handler=()=>callback();ipcRenderer.on('dudidam:show',handler);return()=>ipcRenderer.removeListener('dudidam:show',handler);},
 onSummon:callback=>{if(typeof callback!=='function')return()=>{};const handler=()=>callback();ipcRenderer.on('dudidam:summon',handler);return()=>ipcRenderer.removeListener('dudidam:summon',handler);},
 onDismiss:callback=>{if(typeof callback!=='function')return()=>{};const handler=(_event,reason)=>callback(reason);ipcRenderer.on('dudidam:dismiss',handler);return()=>ipcRenderer.removeListener('dudidam:dismiss',handler);},
 onGlobalPointer:callback=>{if(typeof callback!=='function')return()=>{};const handler=(_event,point)=>callback(point);ipcRenderer.on('dudidam:global-pointer',handler);return()=>ipcRenderer.removeListener('dudidam:global-pointer',handler);}
}));
